RedOrder: Improvements..
- Debian has something fishy idk about yet.

Signed-off-by: Pouria Rezaei <Pouria.rz@outlook.com>

diff --git a/conf.d/vps2deb b/conf.d/vps2deb
--- a/conf.d/vps2deb
+++ b/conf.d/vps2deb
@@ -18,6 +18,32 @@
 
 set -e
 
+if [ "$(id -u)" -ne 0 ]; then
+	echo "This script must be run as root."
+	exit 1
+fi
+
+if ! command -v wget >/dev/null 2>&1; then
+	echo "This script requires wget."
+	exit 1
+fi
+
+if ! command -v docker >/dev/null 2>&1; then
+	echo "This script requires docker."
+	apt update && apt install -y docker.io 2>/dev/null || exit 1
+	apt install -y docker-buildx 2>/dev/null || true
+fi
+
+if ! command -v sgdisk >/dev/null 2>&1 ; then
+	echo "This script requires gdisk for mapping."
+	apt update && apt install -y gdisk 2>/dev/null || exit 1
+fi
+
+if ! command -v rsync >/dev/null 2>&1 ; then
+	echo "rsync required to install extracted Slackware tree."
+	exit 1
+fi
+
 mirror="https://mirror.rackspace.com"
 version="bookworm"
 
@@ -33,7 +59,7 @@ extract_and_prepare() {
 	RUN apt update && apt -y install debootstrap
 	RUN mkdir -p /mnt && \
 		debootstrap --arch amd64 \
-		--include=sudo,bash,dbus,locales,vim,wget,ca-certificates,curl,systemd-timesyncd,zstd,parted,cron,dosfstools,git,openssh-server,build-essential,python3-venv,python3-pip,grub-efi-amd64,open-vm-tools \
+		--include=sudo,dbus,bash,vim,wget,ca-certificates,zstd \
 		$version /mnt $mirror/debian
 
 	FROM scratch
@@ -53,12 +79,7 @@ extract_and_prepare() {
 	tar -xpf /tmp/base.tar -C /Debian
 	rm -f /tmp/base.tar
 
-	if [ -f /etc/resolv.conf ]; then
-		cp -L /etc/resolv.conf /Debian/etc/resolv.conf
-	else
-		(umask 022; printf '%s\n' "nameserver 1.1.1.1") > /Debian/etc/resolv.conf
-	fi
-
+	echo "nameserver 1.1.1.1" > /Debian/etc/resolv.conf
 }
 
 # un_mount() {
@@ -92,7 +113,7 @@ overwrite_system() {
 	rsync -aHAX --numeric-ids --delete-after --exclude=/tmp/** \
 		--exclude=/dev/** --exclude=/proc/** --exclude=/sys/** \
 		--exclude=/Debian/** --exclude=/efi/** --exclude=/boot/** \
-		/Debian/ /
+		/Debian/ / 2>/dev/null || true
 
 	export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/games"
 
@@ -124,12 +145,12 @@ overwrite_system() {
 
 	# Not too raw.. I still want ubuntu stuff a bit
 	apt update
-	apt install -y --no-install-recommends --no-install-suggests \
-		adwaita-icon-theme appstream apt-file at-spi2-core bash bash-completion bc \
-		bcache-tools bolt btrfs-progs build-essential byobu ca-certificates \
-		command-not-found console-setup cron cryptsetup cryptsetup-initramfs curl \
-		dbus dbus-user-session dconf-gsettings-backend distro-info dosfstools \
-		e2fsprogs-l10n eatmydata ed efibootmgr eject ethtool exfatprogs neofetch \
+	apt install -y --no-install-suggests \
+		adwaita-icon-theme appstream apt-file at-spi2-core bash-completion bc \
+		bcache-tools bolt btrfs-progs build-essential byobu command-not-found \
+		console-setup cron cryptsetup cryptsetup-initramfs curl dbus-user-session \
+		dconf-gsettings-backend distro-info dosfstools e2fsprogs-l10n \
+		eatmydata ed efibootmgr eject ethtool exfatprogs neofetch \
 		file fonts-dejavu-core ftp fwupd gdisk gir1.2-packagekitglib-1.0 git \
 		gnome-keyring gnome-keyring-pkcs11 gnupg-l10n gpg-wks-client gpg-wks-server \
 		grub-efi-amd64 gtk-update-icon-cache hdparm hicolor-icon-theme htop \
@@ -163,56 +184,55 @@ overwrite_system() {
 		python3-systemd python3-twisted python3-uritemplate python3-venv \
 		python3-webcolors python3-zipp python3-zope.interface rsync rsyslog \
 		sbsigntool screen sg3-utils sosreport squashfs-tools ssh-import-id strace \
-		sudo systemd-timesyncd tcpdump telnet thermald thin-provisioning-tools time \
+		systemd-timesyncd tcpdump telnet thermald thin-provisioning-tools time \
 		tpm-udev udisks2 upower usb-modeswitch usb.ids usbutils usrmerge uuid-runtime \
-		vim wget wireless-regdb xauth xdg-user-dirs xfsprogs xml-core zerofree zstd
-
-	dpkg-reconfigure locales
+		wireless-regdb xauth xdg-user-dirs xfsprogs xml-core zerofree
 
 	apt dist-upgrade --auto-remove -y
 	apt install -y linux-image-amd64 linux-headers-amd64
+
+	# Making sure one last time
+	dpkg --configure -a
 }
 
 configure_network() {
-	local dev ipaddr gateway conffile
+	local dev ipaddr prefix gateway net_conf
 
-	dev=$(ls /sys/class/net | grep \
-		-Ev '^(lo|docker|veth|br-|virbr|vmnet|zt|wg)' | head -n1)
-	ipaddr=$(ip -4 addr show dev "$dev" 2>/dev/null | \
-		awk '($1=="inet"){print $2; exit}')
-	gateway=$(ip -4 route show default 2>/dev/null | \
-		awk '{print $3; exit}')
-	conffile="/etc/systemd/network/10-default.network"
+	dev=$(ls /sys/class/net | grep -Ev '^(lo|docker|veth|br-|virbr|vmnet|zt|wg)' | head -n1)
+	ipaddr=$(ip -4 -o addr show dev "$dev" scope global | awk '{print $4; exit}')
+	gateway=$(ip -4 route show default | awk '/default/ {print $3; exit}')
+	net_conf="/etc/netplan/00_default.yaml"
 
-	cat > /etc/network/interfaces <<-EOF
-	auto lo
-	iface lo inet loopback
+	mkdir -p /etc/netplan
+	rm -rf /etc/netplan/{.*,*} || true
 
-	auto $dev
-	iface $dev inet dhcp
-	EOF
-
-	if [ -n "$ipaddr" ]; then
-		cat > "$conffile" <<-EOF
-		[Match]
-		Name=$dev
-
-		[Network]
-		Gateway=$gateway
-		Address=$ipaddr
+	if [ -n "$ipaddr" ] && [ -n "$gateway" ]; then
+		prefix=${ipaddr#*/}
+		cat >"$net_conf" <<-EOF
+		network:
+		  version: 2
+		  renderer: networkd
+		  ethernets:
+		    ${dev}:
+		      addresses:
+		        - ${ipaddr}
+		      gateway4: ${gateway}
+		      nameservers:
+		        addresses: [1.1.1.1]
 		EOF
 	else
-		cat > "$conffile" <<-EOF
-		[Match]
-		Name=$dev
-
-		[Network]
-		DHCP=yes
+		cat >"$net_conf" <<-EOF
+		network:
+		  version: 2
+		  renderer: networkd
+		  ethernets:
+		    ${dev}:
+		      dhcp4: true
 		EOF
 	fi
 
-	systemctl enable ssh sshd systemd-networkd \
-		2>/dev/null || true
+	netplan generate
+	netplan apply || true
 }
 
 configure_bootloader() {
